# permissions for end users to view installations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: installation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: helmvm-operator
    app.kubernetes.io/part-of: helmvm-operator
    app.kubernetes.io/managed-by: kustomize
  name: installation-viewer-role
rules:
- apiGroups:
  - embeddedcluster.replicated.com
  resources:
  - installations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - embeddedcluster.replicated.com
  resources:
  - installations/status
  verbs:
  - get
