apiVersion: v1
kind: Service
metadata:
  name: {{ include "mkdocs.fullname" . }}
  labels:
    {{- include "mkdocs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30800 }}
      {{- end }}
  selector:
    {{- include "mkdocs.selectorLabels" . | nindent 4 }}