apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      {{- end}}
  selector:
    {{- include "platform.selectorLabels" . | nindent 4 }}
