# The following patch adds backup and restore labels to the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    replicated.com/disaster-recovery: "infra"
    replicated.com/disaster-recovery-chart: "embedded-cluster-operator"
  name: installations.embeddedcluster.replicated.com
