{{- if .Values.grafana.pdc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-pdc-agent
    name: grafana-pdc-agent
  name: grafana-pdc-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana-pdc-agent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: grafana-pdc-agent
    spec:
      {{- with .Values.grafana.pdc.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: grafana-pdc-agent
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: {{ .Values.grafana.pdc.secretKeys.signingTokenKey }}
              name: {{ .Values.grafana.pdc.existingSecret | default "grafana-pdc-agent" }}
        - name: CLUSTER
          valueFrom:
            secretKeyRef:
              key: {{ .Values.grafana.pdc.secretKeys.clusterKey }}
              name: {{ .Values.grafana.pdc.existingSecret | default "grafana-pdc-agent" }}
        - name: HOSTED_GRAFANA_ID
          valueFrom:
            secretKeyRef:
              key: {{ .Values.grafana.pdc.secretKeys.hostedGrafanaIdKey }}
              name: {{ .Values.grafana.pdc.existingSecret | default "grafana-pdc-agent" }}
        args:
        - -cluster
        - $(CLUSTER)
        - -token
        - $(TOKEN)
        - -gcloud-hosted-grafana-id
        - "$(HOSTED_GRAFANA_ID)"
        image: {{ .Values.grafana.pdc.image.registry }}/{{ .Values.grafana.pdc.image.repository }}:{{ .Values.grafana.pdc.image.tag }}
        imagePullPolicy: {{ .Values.grafana.pdc.image.pullPolicy }}
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          capabilities:
            drop:
              - all
      securityContext:
        runAsUser: 30000
        runAsGroup: 30000
        fsGroup: 30000
{{- end }}