apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: example
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      labels:
        app: example
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          resources:
            limits:
              memory: '64Mi'
              cpu: '50m'
          env:
            - name: APP_SEQUENCE
              value: "{{repl Cursor }}"
            - name: APP_VERSION
              value: "{{repl VersionLabel }}"
            - name: APP_CHANNEL
              value: "{{repl ChannelName }}"
            - name: CONFIG_HOSTNAME
              value: '{{repl ConfigOption "hostname" }}'
            - name: CONFIG_PASSWORD
              value: '{{repl ConfigOption "pw" }}'
