{{- if not .Values.global.pixee.authentication.oidc.embedded.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oidc.fullname" . }}-users
  labels:
    {{- include "oidc.labels" . | nindent 4 }}
type: Opaque
data:
  users.json: {{ .Values.global.pixee.authentication.oidc.embedded.usersJson | b64enc }}
{{- end }}