contents:
  repositories:
    - https://packages.wolfi.dev/os
    - ./packages/
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - ./melange.rsa.pub
  packages:
    - busybox
    - distribution-local # This is expected to be built by melange
    - distribution-local-compat # This is expected to be built by melange

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

paths:
  - path: /etc/docker/registry
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
    recursive: true
  - path: /var/lib/registry
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
    recursive: true
  - path: /etc/ssl/docker
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
    recursive: true
  - path: /auth
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
    recursive: true

entrypoint:
  command: registry

cmd: serve /etc/docker/registry/config.yml