apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
{{- with (include "embedded-cluster-operator.labels" $ | fromYaml) }}
  labels: {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ printf "%s-proxy" (include "embedded-cluster-operator.fullname" $) | trunc 63 | trimAll "-" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: embedded-cluster-operator-proxy
subjects:
- kind: ServiceAccount
  name: {{ include "embedded-cluster-operator.serviceAccountName" $ | trunc 63 | trimAll "-"}}
  namespace: {{ .Release.Namespace }}
