name: publish-staging
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+\-alpha\.[0-9]+'

jobs:

  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
    - name: Get tag
      id: tag
      run: |
        TAG=${{ github.ref_name }}
        echo "tag=${TAG#v}" >> "$GITHUB_OUTPUT"

  package-and-publish-operator:
    runs-on: ubuntu-latest
    needs: [get-tag]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Build melange package
      run: |
        export VERSION=${{needs.get-tag.outputs.tag}}
        make melange
    - name: Publish apko image
      run: |
        export VERSION=${{needs.get-tag.outputs.tag}}
        export IMAGE=replicated/embedded-cluster-operator-image-staging:${VERSION}
        make apko-login \
          REGISTRY=docker.io \
          USERNAME=${{secrets.DOCKERHUB_USER}} \
          PASSWORD=${{secrets.DOCKERHUB_PASSWORD}}
        make apko-publish
        echo ::notice title=digest::$(cat build/digest)

  package-and-publish-helmchart:
    runs-on: 'ubuntu-20.04'
    needs: [get-tag, package-and-publish-operator]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.8.1
    - name: Run Package and Publish
      working-directory: charts/embedded-cluster-operator
      env:
        HELM_USER: ${{secrets.KOTS_HELM_USER_STAGING}}
        HELM_PASS: ${{secrets.KOTS_HELM_PASS_STAGING}}
        HELM_REGISTRY: registry.staging.replicated.com
        CHART_VERSION: ${{needs.get-tag.outputs.tag}}
      run: |
        export OPERATOR_IMAGE_NAME=replicated/embedded-cluster-operator-image-staging
        export OPERATOR_IMAGE_TAG=${CHART_VERSION}
        export CHART_REMOTE=oci://registry.staging.replicated.com/library

        ../../scripts/publish-helm-chart.sh
