name: publish-staging
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+\-alpha\.[0-9]+'

jobs:
  package-and-publish-operator:
    runs-on: ubuntu-latest
    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.0"
    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: registry.staging.replicated.com
        username: ${{secrets.KOTS_HELM_USER_STAGING}}
        password: ${{secrets.KOTS_HELM_PASS_STAGING}}
    - name: Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          registry.staging.replicated.com/library/embedded-cluster-operator-image:${{steps.tag.outputs.tag}}
  package-and-publish-helmchart:
    runs-on: 'ubuntu-20.04'
    needs: package-and-publish-operator
    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1
    - name: Run Package and Publish
      working-directory: charts/embedded-cluster-operator
      env:
        HELM_USER: ${{secrets.KOTS_HELM_USER_STAGING}}
        HELM_PASS: ${{secrets.KOTS_HELM_PASS_STAGING}}
        CHART_VERSION: ${{steps.tag.outputs.tag}}
      run: |
        export OPERATOR_VERSION=${CHART_VERSION%-*}
        export OPERATOR_TAG=${OPERATOR_VERSION}
        export OPERATOR_REGISTRY=registry.staging.replicated.com

        envsubst < Chart.yaml.tmpl > Chart.yaml
        envsubst < values.yaml.tmpl > values.yaml

        export CHART_NAME=`helm package . | rev | cut -d/ -f1 | rev`
        echo pushing ${CHART_NAME} to staging
        helm registry login registry.staging.replicated.com  --username $HELM_USER --password $HELM_PASS
        helm push $CHART_NAME oci://registry.staging.replicated.com/library
